const ActionTypes = {
    SAVE_USER: 'SAVE_USER',
    FETCHED_SERVICES: 'FETCHED_SERVICES',
    ADD_SERVICE: 'ADD_SERVICE',
    UPDATE_SERVICES: 'UPDATE_SERVICES',
    ADD_SPECIAL_OFFER: "ADD_SPECIAL_OFFER",
    FETCHED_SPECIAL_PACKAGE: "FETCHED_SPECIAL_PACKAGE",
    UPDATE_SPECIAL_OFFER: "UPDATE_SPECIAL_OFFER",
    FETCHED_STYLIST: 'FETCHED_STYLIST',
    ADD_STYLIST: "ADD_STYLIST",
    UPDATE_STYLIST: 'UPDATE_STYLIST',
    FETCHED_WORKINGHOURS: 'FETCHED_WORKINGHOURS',
    FETCHED_BOOKINGS: 'FETCHED_BOOKINGS',
    FETCHED_GALLERY: 'FETCHED_GALLERY'
}

export default ActionTypes;
