const ActionTypes = {
    SAVE_USER: 'SAVE_USER',
    FETCHED_SERVICES: 'FETCHED_SERVICES',
    ADD_SERVICE: 'ADD_SERVICE',
    UPDATE_SERVICES: 'UPDATE_SERVICES',
    ADD_SPECIAL_OFFER: "ADD_SPECIAL_OFFER",
    FETCHED_SPECIAL_PACKAGE: "FETCHED_SPECIAL_PACKAGE"
}

export default ActionTypes;
